#! /usr/bin/python
'''
Usage        : haodoo_pp.py list.csv
-h           : this help
list.csv     : .csv file generated by haodoo_spider.py

This script takes an .csv file generated by haodoo_spider.py
and execute the post-processing:

1. Take covers/xxxx.jpg and add it into epub/xxxx.epub to
   create books/xxxx.epub

2. Rename books/xxxx.epub to books/author - title.epub

It's recommended to clean list.csv first with a good editor
(e.g., EditPad Lite).  Sorting, editing, and adding some missing
author names are expected.

Example:

$ haodoo_pp.py haodoo.csv
'''

import sys, getopt, os, shutil, csv
from ebooklib import epub

def usage():
    ''' Display command usage.''' 
    sys.stderr.write(__doc__)
    sys.stderr.flush()

def check_file(fname, ext):
    if not fname.lower().endswith(ext):
        sys.stderr.write(ext.upper() + ": " + fname + " does not have a correct extension!\n")
        sys.exit(2)
    if not os.path.isfile(fname):
        sys.stderr.write("File " + fname + " does not exist!\n")
        sys.exit(2)

def add_cover(epub_fname, jpg_fname):
    book = epub.read_epub(epub_fname)
    with open(jpg_fname, 'rb') as f:
        book.set_cover('cover.jpg', f.read())
    epub.write_epub(epub_fname, book, {})
        
def main(argv):
    # getopt
    try:                                
        opts, args = getopt.getopt(argv, "h")
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    # handle options
    for opt, optarg in opts:
        if opt == '-h':
            usage()                     
            sys.exit()
    if len(args) == 1:
        csv_name = args[0]
    else:
        usage()
        sys.exit()
    # check dirs
    if not os.path.isdir('covers'):
        sys.stderr.write('Cannot find cover images directory "covers/"\n')
        sys.exit(2)
    if not os.path.isdir('epub'):
        sys.stderr.write('Cannot find cover images directory "epubs/"\n')
        sys.exit(2)
    if not os.path.exists('books'):
        os.makedirs('books')
    elif not os.path.isdir('books'):
        sys.stderr.write('Cannot create output directory "books/"\n')
        sys.stderr.write('A file with the same name exists.\n')
        sys.exit(2)
    #
    with open(csv_name, encoding='utf-8') as f:
        reader = csv.reader(f)
        count = 0
        next(reader, None)
        for row in reader:
            auth = row[0]
            title = row[1]
            i = row[2].find('P=')
            epub = row[2][i+2:]
            img = os.path.basename(row[4])
            print(auth + '-' + title, epub, img)
            shutil.copy('epub/' + epub, 'books/' + epub)
            if img != '':
                add_cover('books/' + epub, 'covers/' + img)
            os.replace('books/' + epub, 'books/' + auth + ' - ' + title + '.epub')
            count = count + 1
    print('Total =', count)

if __name__ == "__main__":
    main(sys.argv[1:])
